language: generic
cache:
  directories:
    - $HOME/.ccache
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global: # global settings for all jobs
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
  matrix: # each line is a job
    - ROS_DISTRO="lunar" ROS_REPO=main # overrides the default
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic"
matrix:
  allow_failures:
    - env: ROS_DISTRO="lunar" ROS_REPO=main

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh